### ISSUE TITLE
다대일 관계, N+1문제

### ISSUE THREAD

**Issue by decten** [FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV#12]
## 다대일 관계
다대일 관계 중 양방향이라고 판단(여정으로 쇼핑, 여정들로 여정 조회 가능해야 함)
쇼핑-여정, 여정-여정들
1. 리스트 자료형을 추가
[예시]https://cjw-awdsd.tistory.com/47: 다대일 양방향 참고(리스트&mappedBy)
2. 관계만을 다루는 중간 데이터 테이블 추가
[예시](https://velog.io/@sontulip/how-to-db-design#%EC%9D%B4%EC%83%81%EC%A0%81%EC%9D%B8-%ED%85%8C%EC%9D%B4%EB%B8%94-%EA%B5%AC%EC%A1%B0%EC%97%90-%EB%94%B0%EB%9D%BC-%ED%85%8C%EC%9D%B4%EB%B8%94-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0) : 주문 기록이 고객과 주문 사이의 역할 수행

**근데 저희 프로젝트에서는 중간 데이터 테이블이 리스트 역할 말고는 더 없을 것 같아 리스트 자료형 넣는 방법으로 가는 것이 어떤가 합니다 -> 질문**

## N+1문제
아직 발생하진 않았지만, [해결책](https://velog.io/@jinyoungchoi95/JPA-%EB%AA%A8%EB%93%A0-N1-%EB%B0%9C%EC%83%9D-%EC%BC%80%EC%9D%B4%EC%8A%A4%EA%B3%BC-%ED%95%B4%EA%B2%B0%EC%B1%85#fetch-join-%ED%95%98%EB%A9%B4-%EB%A7%8C%EB%8A%A5-%EC%9D%80-%EC%95%84%EB%8B%99%EB%8B%88%EB%8B%A4)
distinct+fetch join

**Comment by whdgns5059** [comment]
DB관점에서 보면 1:N에서 1의 엔티티는 N의 정보를 가지고 있지 않아도 됩니다. 하지만 객체지향 설계를 추구하는 JPA에선 Trip은 Itinerary를 가지고 있어야 하는 1:N 양방향 관계이므로 Trip은 List<Itinerary>를 가지고 있어야 하는게 맞네요.

말씀해주신 MappedBy 기능을 이용해 1:N 양방향 관계를 맺는게 좋은 방향이라 생각 됩니다.

2번은 여행과 여정은 1:N 관계라서 N:N 문제에서 사용하는 테이블은 사용하지 않아도 될거라 생각합니다. 여행과 여정의 각각의 연관 관계가 명확하게 1:N으로 연관 되니까요.

양방향관계 설계시에 문제가 생기는 부분은 보내주신 링크의 lazy  fetch join을 이용 하면 좋을 것 같습니다,

**Comment by decten** [comment]
[다음과 같은 방식](https://velog.io/@yuseogi0218/JPA-%EC%96%91%EB%B0%A9%ED%96%A5-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84)으로 구현했습니다.
연관 관계의 주인만이 데이터베이스의 외래 키의 값을 변경할 수 있다

[다대일에서는 N이 연관 관계의 주인](https://covenant.tistory.com/260)
