### ISSUE TITLE
패키지 구조와 setter 대체

### ISSUE THREAD

**Issue by decten** [FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV#14]
## 패키지 구조
저희가 DDD를 도입해서 프로젝트를 진행하고 있고, 그에 맞춰 패키지 설계를 해야 하는데 레이어드로 점점 돌아가게 되더라구요
그래서 [참고 링크](https://cheese10yun.github.io/spring-guide-directory/)를 가져왔고, 다른 ddd 깃 허브 코드 구조들과 비슷하면서도 어떻게 설계해야 하는지 이해하기 쉬웠습니다.

**이에 맞춰 지금 설계하거나 아님 나중에 제가 마지막에 바꾸면 어떨까 싶습니다**
 ex) repository -> dao

## Setter 대체
위랑 같은 [블로그](https://cheese10yun.github.io/code-design/#null)인데, 
> 테스트 코드에서 필요한 데이터를 sql 파일, json 파일로 처리

방법이 좋아서 같이 가져왔습니다.

**Comment by sungjiwoon** [comment]
참고하겠습니다. 감사합니다!

**Comment by ghrltjdtprbs** [comment]
링크 걸어주신 블로그 잘 읽어봤습니다! 
하지만 DDD에서도 Repository와 DAO는 서로 다른 역할을 한다고 알고 있습니다. 블로그의 결론에도 나와있듯이 도메인 형이라는 큰 틀 안에서 디렉토리는 프로젝트의 요구 사항, 아키텍처, 개발자의 선호에 따라 달라질 수 있습니다. 
사실 저희가 도메인 별로 패키지를 나누기는 했지만, 그것 만으로 DDD를 도입했다고 보기 어렵습니다. 
DDD를 적용하려면 패키지 설계 말고도 훨씬 더 많은 고려 사항이 있으니 만약 DDD를 적용하고 싶다면 리팩토링 때 더 자세하게 회의를 해 봐야 할 것 같아요!

**Comment by decten** [comment]
아 저는 repository를 dao로 바꾸는 것은 아니고 dao 패키지 안에 repository와dao 클래스를 넣는 방법으로 생각했습니다
그런데 저희가 model 없이 엔터티만 존재하는 상황이라 많이 다르긴 하더라구요
그리고 DDD를 도입 안 해도 상관 없는데, 지금은 혼재 된 느낌이라 레이어드던 DDD던 하나의 방법으로 통일하려는 목적이 컸습니다😀
