### ISSUE TITLE
entity 에서 @Setter 사용 관해서요!

### ISSUE THREAD

**Issue by sungjiwoon** [FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV#17]
entity 안에서 @Setter 를 사용하고,
서비스 로직에서 필드를 set 해주면 자동으로 update 해주어서 편의가 좋긴합니다.

다만 많은 개발자들이 @Setter를 지양하고 있는데, 
그렇다면 여정 수정,삭제 시에 어떻게 코드를 짜면 좋을까요?

1. 매번 builder를 사용하여 객체를 재정의 한다. -> 지저분해질수있음.

2. 밑의 예제처럼 짠다 -> 직관적인 값 수정, 벗 엔티티 클래스에 메소드 들어감

만약 순서를 update를 하고 싶다면 예제입니다.

```java
@Getter
@Entity
public class Itinerary {
	
        @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long itineraryId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tripId")
    private Trip tripId;

    @Column(nullable = false)
    private String itineraryName;

    @Column(nullable = false)
    private Integer itineraryOrder;

    @ColumnDefault("false")
    private Boolean isDeleted;

    private LocalDateTime deletedAt;

    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;
    
    public void updateItineraryOrder(Long id, Integer newOrder) {
        this.id = id; ...
        this.itineraryOrder = newOrder;
       ....
    }
}
``` 

(출처 : [@setter 지양 이유](https://velog.io/@langoustine/setter-%EC%A7%80%EC%96%91-%EC%9D%B4%EC%9C%A0))

3. 다른 방법 뭐가 있을까요..

**Comment by decten** [comment]
[참고](https://velog.io/@backfox/setter-%EC%93%B0%EC%A7%80-%EB%A7%90%EB%9D%BC%EA%B3%A0%EB%A7%8C-%ED%95%98%EA%B3%A0-%EA%B0%80%EB%B2%84%EB%A6%AC%EB%A9%B4-%EC%96%B4%EB%96%A1%ED%95%B4%EC%9A%94)
여기를 참고했는데, 그냥 메서드가 아니고 엔터티의 @Setter 대신 더 자세히 들어간 Setter라서 2번 방법을 생각했습니다

**Comment by whdgns5059** [comment]
저는 2번의 방식이 나쁘지 않다고 생각합니다. 
비지니스 로직에서 필요하다면 엔티티가 메서드를 가져도 문제 될 건 없다고 생각합니다.
물론 엔티티 하나에 메서드가 수십개가 되면 분명 뭔가 문제가 있는 거겠지만요

예전에 이거에 대해서 멘토님이나, 객체지향 설계 강의에서 들었던 얘기 중 하나 인데요.
물론 개발 방법론상 엔티티는 객체의 값만 가지는게 맞습니다. 하지만 객체의 책임과 메서드 업무가 명확하다면 엔티티가 메서드를 가져도 문제 될 건 없다고 한 기억이 있네요
