### ISSUE TITLE
RFP 일시의 공통유틸리티 클래스에 대한 이슈

### ISSUE THREAD

**Issue by whdgns5059** [FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV#18]
![image](https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/40512982/492db34b-6acd-4dc7-aaa9-7a5942901f4a)

![image](https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/40512982/af7edbdd-e58a-4b98-9b07-5b95ab0b750d)

해당 기능에 대해서 저희가 어느정도 자유롭게 정의해서 사용하면 될 것 같습니다.

**Comment by decten** [comment]
공통: 사용자가 보낸 쿼리를 localdatetime에 맞춰 수정 후 변환

1. 여행과 여정의 공통 정보인 날짜만을 다루는 유틸리티 클래스
2. 여정들만을 다뤄서 날짜와 시간을 다루는 유틸리티 클래스
ex) "startDate": "2023-11-01T08:00:00"

이렇게 생각했습니다. 
그런데 지금 작성하면서 생각해보니, 여정에서 시간도 받아야 하는데 날짜만을 받으면 시간 처리가 애매해져서 2번이 괜찮다고 생각합니다.

**Comment by whdgns5059** [comment]
**일시에 대한 공통 유틸리티 클래스**
1. 날짜가 "2020-12-12T10:00:00" 처럼 오지 않을 수도 있음 "2020년 10월 20일", "2020-10-20" 식의 다양한 날짜를 LocalDate 형식으로 바꿔주는 유틸리티 클래스.(여행에서 사용)
2. 위의 기능에서 시간까지 포함하는 유틸리티 클래스 (여정에서 사용)
를 만들어서 Dto에선 문자열로 받고 이를 서비스에서 LocalDate, LocalDateTime으로 변환 해주는 공통의 유틸리티 클래스

**위치정보**
교통수단의 출발지, 도착지,  숙소의 숙박지, 체류지의 장소를 카카오 API를 통해 데이터를 가져와 1번째 응답을 저장. 
사용자의 입력과 카카오API로 조회한 상세정보(ex:도로명주소)를 둘다 저장하고
여행 상세 조회시 출력

이렇게 하면 될 거라고 생각합니다.

**Comment by ghrltjdtprbs** [comment]
지금 다시 읽어보니 요구사항에 여행은 이름, 일정, 국내외 여부만 포함이 되네요. 그런데 프로젝트 정의서에는 일정정보에 위치 정보까지 추가해서 출력하라고 나와있습니다!
현재 저희가 기획한 여행 정보 등록 로직에서는 여행 장소(위치) 데이터가 포함되지 않습니다.
정의서 8번 문항은 이 여행 일정에 위치데이터를 추가하라는 소리 같네요!

ex)
{
  "tripName": "영국 여행",
  "startDate": "2023-11-01T08:00:00",
  "endDate": "2023-11-10T20:00:00",
  "isDomestic": true
}
현재 저희가 여행 정보 등록을 위해 사용자에게 받는 데이터값입니다. 
여기서 여행 장소(위치)데이터는 들어가지 않고, 여행 이름으로 위치를 추측하는 방식이네요.

일시 정보가 공통 유틸리티에 들어간다는 것은 아직 좀 더 생각해 봐야 할 것 같습니다...우선 저희 기획에 누락된 부분이 있어 먼저 말씀드립니다.

**Comment by ghrltjdtprbs** [comment]
만약 일정 정보에 따로 위치 데이터를 추가하는 방식이라면 일정 정보를 따로 관리해야 하는데 혹시 이런 부분을 공통 유틸리티로 관리하라는 소리가 아닌지 추측이 되네요...

**Comment by whdgns5059** [comment]
> 지금 다시 읽어보니 요구사항에 여행은 이름, 일정, 국내외 여부만 포함이 되네요. 그런데 프로젝트 정의서에는 일정정보에 위치 정보까지 추가해서 출력하라고 나와있습니다! 현재 저희가 기획한 여행 정보 등록 로직에서는 여행 장소(위치) 데이터가 포함되지 않습니다. 정의서 8번 문항은 이 여행 일정에 위치데이터를 추가하라는 소리 같네요!
> 
> ex) { "tripName": "영국 여행", "startDate": "2023-11-01T08:00:00", "endDate": "2023-11-10T20:00:00", "isDomestic": true } 현재 저희가 여행 정보 등록을 위해 사용자에게 받는 데이터값입니다. 여기서 여행 장소(위치)데이터는 들어가지 않고, 여행 이름으로 위치를 추측하는 방식이네요.
> 
> 일시 정보가 공통 유틸리티에 들어간다는 것은 아직 좀 더 생각해 봐야 할 것 같습니다...우선 저희 기획에 누락된 부분이 있어 먼저 말씀드립니다.

여행에서는 여행의 제목, 기간만 정의 하고, 여정에서 상세 위치정보를 관리하고 있으니 여정에서 위치정보를 관리하면 될 거 같습니다.
저는 정의서에 일정이란 용어를 여정과 같은 의미로 보고 있습니다.

**Comment by ghrltjdtprbs** [comment]
> 여행에서는 여행의 제목, 기간만 정의 하고, 여정에서 상세 위치정보를 관리하고 있으니 여정에서 위치정보를 관리하면 될 거 같습니다. 저는 정의서에 일정이란 용어를 여정과 같은 의미로 보고 있습니다.

그렇다고 가정을 해도 여정 정보에는 숙박 위치, 이동 위치 등 많은 위치 정보가 들어가는데 해당 여행을 대표하는 위치 정보는 없는 것 같아서요! 
전체 여행 정보를 출력할 때 각 여행의 상세 여정정보가 출력 되지 않는 만큼 해당 여행의 대표 위치 정보는 추가해야 할 것 같습니다.

**Comment by sungjiwoon** [comment]
일시에 대한 공통 유틸리티 클래스 생성해서 활용해라
저희가 일시에 대한 걸 활용하란 뜻으로 해석했습니다.

제가 트립.com 이라는 여행 관리 어플을 사용해봤는데
여정에 대한 날짜 혹은 시간을 입력하면 
몇 박인지, 혹은 걸리는 시간을 출력했어요.

그래서 일시 (startDate, endDate)를 입력하면
#### 유틸리티 클래스로 몇 박인지, 얼마나 시간이 소요되는지 계산해주는 클래스로 활용하는 것도 
요구사항에 들어가지 않을까요?

#### 예시사진
![image](https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/59862752/09b37a49-b7bd-4992-b60a-04e409c62ac5)

![KakaoTalk_Photo_2023-10-25-15-24-33](https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/59862752/a6137c71-fbb0-44a3-995e-5c442fea9fd7)

**Comment by ghrltjdtprbs** [comment]
저는 좋은 것 같습니다! 실제로 야놀자 어플에서도 날짜를 입력하면 몇 박인지 자동으로 출력을 해주는 기능이 있더라구요... 이걸 말하는게 아닌가 싶기도 하네요

**Comment by whdgns5059** [comment]
아 이해가 가네요. 네 저도 지운님이 얘기하신거에 동의합니다.

**Comment by whdgns5059** [comment]
**회의 내역**

날짜에 대한 validation : DateTimeFormat을 이용한 Validation으로 처리 합니다.

여행, 여정 소요 기간에 대한 공통 유틸리티 : 여행 시작일,종료일, 여정의 각각 출발,도착일시 등 데이터를 입력 받아 DB에 저장하지 않고 계산하여 응답에 담아 보내줍니다.

위치 정보 : 위치 정보는 지도 좌표상의 x,y 좌표를 의미한다고 정의(해외의 경우도 있기 댸문에 도로명주소 아님) 여행에서는 위치정보를 관리 하지 않습니다. 
여정의 숙박과, 체류 항목의 숙박지, 체류리 정보를 이용 Google API를 통해 좌표를 가져와 등록, 수정시에 DB에 저장 합니다.
GoogleAPI 도 공통 유틸리티로 작성합니다.

혹시 틀렸거나 잘 못 전달 되는 부분 있으면 말씀 해 주세요

**Comment by sungjiwoon** [comment]
좋습니다
여행, 여정 소요 기간 보낼 때에는 문자열로 보내는게 어떨까요?
21일 4시간 3분 -> "21:4:3"
8시간 30분 -> "8:30"
30분 -> "30"
응답 에서 spilit 함수 써서 쪼개면 될 것같습니다.
