### ISSUE TITLE
상속 클래스에서 Response DTO 매핑

### ISSUE THREAD

**Issue by decten** [FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV#30]
## 현재 상황
Itinerary로 받아올 땐 하위 클래스 내용이 잘 매핑 돼서 출력이 됐는데, ItineraryResponse에서는 Itinerary 내용만 출력할 뿐 그 하위 내용(movement, stay, lodgement)가 매핑이 안 됨
<img width="530" alt="image" src="https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/52107658/2ad9e0b2-26b1-471f-9fe1-c2ea6b8b3c0d">
<img width="682" alt="image" src="https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/52107658/2b62b9a0-740f-43c9-91f3-4a2190208e74">

## 기존 대처
Itinerary로 받은 리스트를 for문과 switch로 분기하면서 ItineraryResponse 리스트를 만들고 있음
<img width="499" alt="image" src="https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/52107658/c0f53f5c-e9cc-4f4f-a97a-24e488389bd1">

## 해결책 후보
[for 문을 대체하는 방법](https://pjh3749.tistory.com/248)
**근본적인 해결책이 필요함**

**Comment by sungjiwoon** [comment]
다음과 같이 해결하였습니다.

#### 코드 
- 다대일 관계를 이용.
- instanceof, 다형성활용
![image](https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/59862752/4ec44adf-b5ff-4070-9288-970d2348d606)

#### 결과화면
<img width="601" alt="스크린샷 2023-10-27 오전 11 31 23" src="https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/59862752/af3801e8-f47e-425e-b80a-fb9bf7f7ec8f">
