### ISSUE TITLE
inheritance 전략

### ISSUE THREAD

**Issue by decten** [FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV#8]
## 의견
저희는 조회를 많이 하고, 테이블이 크지 않아 @Inheritance(stragegy=InheritanceType.SINGLE_TABLE)를 생각했습니다.
[참고 링크](https://jaime-note.tistory.com/381)

**Comment by whdgns5059** [comment]
말씀 하신대로 TABLE_PER_CLASS의 경우 일반적으로 추천을 하지 않는군요, 제가 JOINED 랑 헷갈린거 같아요.

저는 single_table 전략에 대해서 null 허용이란 부분이 데이터 정합성에 문제가 생길거 같아서
JOINED를 하는게 어떨까 합니다. 

DB 관점으로 봤을때 JOINED가 일반적으로 통용되고.
1~2개의 같은DB의 테이블 JOIN관계는 indexing된 테이블 간엔 성능저하를 고민 하지 않아도 될 정도로 미미하다고 알고있어요.

물론 join관계가 생기면 특수한 경우에 쿼리를 직접 작성해야 하지만 현재의 구조상 쿼리를 직접 구현할정도의 난이도는 없는것 같습니다. 
테이블 join 관계는 너무나도 흔한 케이스기도 하구요

**Comment by decten** [comment]
네 null 부분 때문에 joined가 좋을 것 같습니다.
의견 감사합니다!

**Comment by whdgns5059** [comment]
해당부분은 그럼 JOINED 로바꾸고 몇몇 엔티티에 대해 추가 설명을 더 적은뒤에 제가 PR날릴까요?

**Comment by decten** [comment]
넵 감사합니다👍

**Comment by whdgns5059** [comment]
> 넵 감사합니다👍

댓글을 제가 삭제해서 ㅋㅋ 
entity 정보 명시하는거 작업하도록 하겠습니다
